repository:
  default_branch: main
  allow_auto_merge: true
  delete_branch_on_merge: true
  has_wiki: false

branch_protection:
  - pattern: "main"
    required_status_checks:
      strict: true
      contexts: ["ci/checks"]
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
