name: Apply Safe Settings
on:
  push:
    branches:
      - main
jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Apply Safe Settings
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const settings = yaml.load(fs.readFileSync('.github/safe-settings.yml', 'utf8'));
            console.log("Applying settings: ", settings);
